# Generated by Django 5.2.7 on 2025-10-25 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0004_alter_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('yookassa', 'ЮKassa')], db_index=True, max_length=16, verbose_name='Платежный провайдер')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('description', models.CharField(max_length=100, verbose_name='Назначение платежа')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Дата платежа')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='planner.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платеж за подписку',
                'verbose_name_plural': 'Платежи за подписку',
            },
        ),
    ]
