# Generated by Django 5.2.7 on 2025-10-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payment_id',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='Идентификатор платежа'),
            preserve_default=False,
        ),
    ]
