# Generated by Django 4.2.25 on 2025-10-22 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Аллергия')),
            ],
        ),
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Тип диеты')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('recipe', models.TextField(blank=True, default='', verbose_name='Рецепт приготовления')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Фото блюда')),
                ('category', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('dessert', 'Десерт')], default='lunch', max_length=50, verbose_name='Категория блюда')),
                ('diet_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.diettype', verbose_name='Тип меню')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ограничение по стоимости')),
                ('count_of_persons', models.IntegerField(default=1, verbose_name='Количество персон')),
                ('breakfast', models.BooleanField(default=True, verbose_name='Завтрак')),
                ('lunch', models.BooleanField(default=True, verbose_name='Обед')),
                ('dinner', models.BooleanField(default=True, verbose_name='Ужин')),
                ('dessert', models.BooleanField(default=False, verbose_name='Десерт')),
                ('subscription_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('allergies', models.ManyToManyField(blank=True, to='planner.allergy', verbose_name='Аллергии')),
                ('diet_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.diettype', verbose_name='Тип диеты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название ингредиента')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за единицу')),
                ('callories', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Калорийность')),
                ('unit', models.CharField(choices=[('g', 'Граммы'), ('ml', 'Миллилитры'), ('pcs', 'Штуки'), ('tbsp', 'Столовые ложки'), ('tsp', 'Чайные ложки')], default='g', max_length=10, verbose_name='Единица измерения')),
                ('allergens', models.ManyToManyField(blank=True, to='planner.allergy', verbose_name='Аллергены')),
            ],
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(through='planner.DishIngredient', to='planner.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
