# Generated by Django 5.2.7 on 2025-10-24 14:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_subscriptionplan_alter_dish_diet_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name': 'Аллергия', 'verbose_name_plural': 'Аллергии'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='dishingredient',
            options={'verbose_name': 'Ингридиент блюда', 'verbose_name_plural': 'Ингридиенты блюд'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='callories',
            new_name='calories',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='diet_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='persons_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_end_date',
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Завтраки'), ('lunch', 'Обеды'), ('dinner', 'Ужины'), ('dessert', 'Десерты')], db_index=True, default='lunch', max_length=50, verbose_name='Категория блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='diet_type',
            field=models.CharField(blank=True, choices=[('classic', 'Классическое'), ('low_carb', 'Низкоуглеводное'), ('vegetarian', 'Вегетарианское'), ('keto', 'Кето')], db_index=True, null=True, verbose_name='Тип меню'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(choices=[('classic', 'Классическое'), ('low_carb', 'Низкоуглеводное'), ('vegetarian', 'Вегетарианское'), ('keto', 'Кето')], db_index=True, verbose_name='Тип диеты')),
                ('selected_meal_types', models.JSONField(default=list, verbose_name='Выбранные приёмы пищи')),
                ('persons_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Количество персон')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала подписки')),
                ('end_date', models.DateField(verbose_name='Дата окончания подписки')),
                ('allergies', models.ManyToManyField(blank=True, to='planner.allergy', verbose_name='Аллергии')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='planner.subscriptionplan', verbose_name='Тарифный план')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка пользователя',
                'verbose_name_plural': 'Подписки пользователей',
            },
        ),
    ]
