# Generated by Django 5.2.7 on 2025-10-25 14:27

import planner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_allergy_options_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=planner.models.get_avatar_upload_path, verbose_name='Аватар'),
        ),
    ]
